### ISSUE TITLE
version 1.0 checklist

### ISSUE THREAD

**Issue by OndrejHome** [OndrejHome/fast-vm#14]
- [x] make option to allow VM deletion only to owner of VM note or root
- [x] automatically create empty note on VM creation - this shows the username of VM owner
- [ ] _tentative:_ more verbose accounting of fast-vm usage - counting how much VMs and time user spent using fast-vm or for how long the VMs were running (maybe also with consumed CPU/memory/disk usage)
- [x] add configuration option for notes directory to configure-fast-vm
- [x] check if upgrading fast-vm respects /etc/sudoers.d/... settings and doesn't overwrite them
- [x] re-check again issue with re-use of same VM number - create machine XX, boot it up, delete XX, create new machine with same XX and boot up, observe if IP assignment is correct

**Comment by OndrejHome** [comment]
Version 0.9.5 addresses one issue discovered when testing fast-vm on RHEL/CentOS. If upgrading from previous versions, then `fast-vm-net-cleanup` must be used to install workaround for this.
Kepping this issue still open as there are still some outstanding things before 1.0

**Comment by OndrejHome** [comment]
discarding need for more verbose accounting. fast-vm 1.0 was released so closing the issue.
