### ISSUE TITLE
RHEL 8 compatibility check

### ISSUE THREAD

**Issue by OndrejHome** [OndrejHome/fast-vm#46]
Idea:
  Check what needs to be changed for `fast-vm` to run properly on RHEL 8.
### TODO
  - [x] check firewalling, in default installation the VMs gets IP only when `firewalld` gets stopped
  - [x] figure out how to properly fix the firewall issue
  - [x] build custom `qemu-kvm` package as for RHEL/CentOS 7.x and document in `PACKAGING`
    - not all dependencies for `qemu-kvm` seems to be present in Beta repos :/
    - on RHEL 8.0 it is possible to buld `qemu-kvm` package with some difficulties - https://access.redhat.com/discussions/4342891
  - [x] build custom `seabios` package as for RHEL/CentOS 7.x and document in `PACKAGING`
    - configuration options seems to changed places - check if the `config.seabios-256k` is still relevant or if it takes defaults from `config.seabios-128k`
  - [x] update `docs/user_guide.txt` to reflect any specifics of RHEL8
  - [x] test out older images that requires changes `qemu-kvm` and `seabios` packages to confirm that they works well

**Comment by OndrejHome** [comment]
Seems that RHEL 8 contains the libvirt that uses firewalld zones, but it actually doesn't put the custom names interfaces into `libvirt` zone that allows forwarding of traffic, DHCP and other usual services for NAT libvirt network. There is a short list of 10 most common bridge names defined in the `/usr/lib/firewalld/zones/libvirt.xml`. For any custom named bridge the following commands are needed to get it into working `libvirt` zone.
~~~
firewall-cmd --zone=libvirt --change-interface=fastvm-nat
firewall-cmd --zone=libvirt --change-interface=fastvm-nat --permanent
~~~

**Comment by OndrejHome** [comment]
As of testing now with RHEL 8.0 it seems that firewall is OK. All packages `libvirt-daemon-driver-network.x86_64` starting from version `4.5.0-23.module+el8+2800+2d311f65` seems to be OK.

**Comment by OndrejHome** [comment]
old images works well even at RHEL/CentOS 8 if there is qemu with megaraid SCSI support. Getting that builded automatically is however quite painful as the COPR seems to be broken for EPEL 8 and qemu related packages. The issue is the missing 'libssh2-devel' which is not accepted even when provided from same repository so there is no nice/easy way to distribute the RPMs that are needed. Still following the `PACKAGING` document is a way how to build the needed things. As this is not directly impacting fast-vm I will close this issue because this was the last thing on list here.
